/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EpisodeList: typeof import('./src/components/EpisodeList.vue')['default']
    EpisodePlayer: typeof import('./src/components/EpisodePlayer.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    MediaFileStreamsSelector: typeof import('./src/components/MediaFileStreamsSelector.vue')['default']
    MoviePlayer: typeof import('./src/components/MoviePlayer.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Recentcarousel: typeof import('./src/components/Recentcarousel.vue')['default']
    RecentMovies: typeof import('./src/components/RecentMovies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TVShowsSeasonExpansion: typeof import('./src/components/TVShowsSeasonExpansion.vue')['default']
    TVShowsSlide: typeof import('./src/components/TVShowsSlide.vue')['default']
  }
}
