/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Categorie
 */
export interface Categorie {
    /**
     * 
     * @type {string}
     * @memberof Categorie
     */
    id?: string;
}

/**
 * Check if a given object implements the Categorie interface.
 */
export function instanceOfCategorie(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategorieFromJSON(json: any): Categorie {
    return CategorieFromJSONTyped(json, false);
}

export function CategorieFromJSONTyped(json: any, ignoreDiscriminator: boolean): Categorie {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function CategorieToJSON(value?: Categorie | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

