/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategorieEntity } from './CategorieEntity';
import {
    CategorieEntityFromJSON,
    CategorieEntityFromJSONTyped,
    CategorieEntityToJSON,
} from './CategorieEntity';
import type { NodeEntity } from './NodeEntity';
import {
    NodeEntityFromJSON,
    NodeEntityFromJSONTyped,
    NodeEntityToJSON,
} from './NodeEntity';

/**
 * 
 * @export
 * @interface DiskEntity
 */
export interface DiskEntity {
    /**
     * 
     * @type {string}
     * @memberof DiskEntity
     */
    id?: string;
    /**
     * 
     * @type {NodeEntity}
     * @memberof DiskEntity
     */
    nodeEntity?: NodeEntity;
    /**
     * 
     * @type {CategorieEntity}
     * @memberof DiskEntity
     */
    categorieEntity?: CategorieEntity;
    /**
     * 
     * @type {string}
     * @memberof DiskEntity
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof DiskEntity
     */
    diskType?: DiskEntityDiskTypeEnum;
}


/**
 * @export
 */
export const DiskEntityDiskTypeEnum = {
    Library: 'LIBRARY',
    Cache: 'CACHE'
} as const;
export type DiskEntityDiskTypeEnum = typeof DiskEntityDiskTypeEnum[keyof typeof DiskEntityDiskTypeEnum];


/**
 * Check if a given object implements the DiskEntity interface.
 */
export function instanceOfDiskEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DiskEntityFromJSON(json: any): DiskEntity {
    return DiskEntityFromJSONTyped(json, false);
}

export function DiskEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'nodeEntity': !exists(json, 'nodeEntity') ? undefined : NodeEntityFromJSON(json['nodeEntity']),
        'categorieEntity': !exists(json, 'categorieEntity') ? undefined : CategorieEntityFromJSON(json['categorieEntity']),
        'path': !exists(json, 'path') ? undefined : json['path'],
        'diskType': !exists(json, 'diskType') ? undefined : json['diskType'],
    };
}

export function DiskEntityToJSON(value?: DiskEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nodeEntity': NodeEntityToJSON(value.nodeEntity),
        'categorieEntity': CategorieEntityToJSON(value.categorieEntity),
        'path': value.path,
        'diskType': value.diskType,
    };
}

