/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFile } from './MediaFile';
import {
    MediaFileFromJSON,
    MediaFileFromJSONTyped,
    MediaFileToJSON,
} from './MediaFile';

/**
 * 
 * @export
 * @interface MediaFileStream
 */
export interface MediaFileStream {
    /**
     * 
     * @type {string}
     * @memberof MediaFileStream
     */
    id?: string;
    /**
     * 
     * @type {MediaFile}
     * @memberof MediaFileStream
     */
    mediaFile?: MediaFile;
    /**
     * 
     * @type {number}
     * @memberof MediaFileStream
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaFileStream
     */
    codecName?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaFileStream
     */
    codecType?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaFileStream
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaFileStream
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaFileStream
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaFileStream
     */
    title?: string;
}

/**
 * Check if a given object implements the MediaFileStream interface.
 */
export function instanceOfMediaFileStream(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFileStreamFromJSON(json: any): MediaFileStream {
    return MediaFileStreamFromJSONTyped(json, false);
}

export function MediaFileStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFileStream {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'mediaFile': !exists(json, 'mediaFile') ? undefined : MediaFileFromJSON(json['mediaFile']),
        'index': !exists(json, 'index') ? undefined : json['index'],
        'codecName': !exists(json, 'codecName') ? undefined : json['codecName'],
        'codecType': !exists(json, 'codecType') ? undefined : json['codecType'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function MediaFileStreamToJSON(value?: MediaFileStream | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'mediaFile': MediaFileToJSON(value.mediaFile),
        'index': value.index,
        'codecName': value.codecName,
        'codecType': value.codecType,
        'width': value.width,
        'height': value.height,
        'language': value.language,
        'title': value.title,
    };
}

