/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeEntity } from './EpisodeEntity';
import {
    EpisodeEntityFromJSON,
    EpisodeEntityFromJSONTyped,
    EpisodeEntityToJSON,
} from './EpisodeEntity';
import type { SeasonEntity } from './SeasonEntity';
import {
    SeasonEntityFromJSON,
    SeasonEntityFromJSONTyped,
    SeasonEntityToJSON,
} from './SeasonEntity';
import type { ShowEntity } from './ShowEntity';
import {
    ShowEntityFromJSON,
    ShowEntityFromJSONTyped,
    ShowEntityToJSON,
} from './ShowEntity';

/**
 * 
 * @export
 * @interface MetadataEntity
 */
export interface MetadataEntity {
    /**
     * 
     * @type {string}
     * @memberof MetadataEntity
     */
    id?: string;
    /**
     * 
     * @type {ShowEntity}
     * @memberof MetadataEntity
     */
    showEntity?: ShowEntity;
    /**
     * 
     * @type {SeasonEntity}
     * @memberof MetadataEntity
     */
    seasonEntity?: SeasonEntity;
    /**
     * 
     * @type {EpisodeEntity}
     * @memberof MetadataEntity
     */
    episodeEntity?: EpisodeEntity;
    /**
     * 
     * @type {string}
     * @memberof MetadataEntity
     */
    sourceUri?: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataEntity
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataEntity
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof MetadataEntity
     */
    released?: Date;
}

/**
 * Check if a given object implements the MetadataEntity interface.
 */
export function instanceOfMetadataEntity(value: object): boolean {
    return true;
}

export function MetadataEntityFromJSON(json: any): MetadataEntity {
    return MetadataEntityFromJSONTyped(json, false);
}

export function MetadataEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'showEntity': json['showEntity'] == null ? undefined : ShowEntityFromJSON(json['showEntity']),
        'seasonEntity': json['seasonEntity'] == null ? undefined : SeasonEntityFromJSON(json['seasonEntity']),
        'episodeEntity': json['episodeEntity'] == null ? undefined : EpisodeEntityFromJSON(json['episodeEntity']),
        'sourceUri': json['sourceUri'] == null ? undefined : json['sourceUri'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'released': json['released'] == null ? undefined : (new Date(json['released'])),
    };
}

export function MetadataEntityToJSON(value?: MetadataEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'showEntity': ShowEntityToJSON(value['showEntity']),
        'seasonEntity': SeasonEntityToJSON(value['seasonEntity']),
        'episodeEntity': EpisodeEntityToJSON(value['episodeEntity']),
        'sourceUri': value['sourceUri'],
        'title': value['title'],
        'description': value['description'],
        'released': value['released'] == null ? undefined : ((value['released']).toISOString()),
    };
}

