/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeEntity
 */
export interface NodeEntity {
    /**
     * 
     * @type {string}
     * @memberof NodeEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeEntity
     */
    name?: string;
}

/**
 * Check if a given object implements the NodeEntity interface.
 */
export function instanceOfNodeEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeEntityFromJSON(json: any): NodeEntity {
    return NodeEntityFromJSONTyped(json, false);
}

export function NodeEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function NodeEntityToJSON(value?: NodeEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

