/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeEntity
 */
export interface NodeEntity {
    /**
     * 
     * @type {string}
     * @memberof NodeEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeEntity
     */
    name: string;
}

/**
 * Check if a given object implements the NodeEntity interface.
 */
export function instanceOfNodeEntity(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function NodeEntityFromJSON(json: any): NodeEntity {
    return NodeEntityFromJSONTyped(json, false);
}

export function NodeEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function NodeEntityToJSON(value?: NodeEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

