/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeEntity } from './EpisodeEntity';
import {
    EpisodeEntityFromJSON,
    EpisodeEntityFromJSONTyped,
    EpisodeEntityToJSON,
} from './EpisodeEntity';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageEpisodeEntity
 */
export interface PageEpisodeEntity {
    /**
     * 
     * @type {number}
     * @memberof PageEpisodeEntity
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageEpisodeEntity
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageEpisodeEntity
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageEpisodeEntity
     */
    size?: number;
    /**
     * 
     * @type {Array<EpisodeEntity>}
     * @memberof PageEpisodeEntity
     */
    content?: Array<EpisodeEntity>;
    /**
     * 
     * @type {number}
     * @memberof PageEpisodeEntity
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageEpisodeEntity
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageEpisodeEntity
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageEpisodeEntity
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageEpisodeEntity
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageEpisodeEntity
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageEpisodeEntity interface.
 */
export function instanceOfPageEpisodeEntity(value: object): boolean {
    return true;
}

export function PageEpisodeEntityFromJSON(json: any): PageEpisodeEntity {
    return PageEpisodeEntityFromJSONTyped(json, false);
}

export function PageEpisodeEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageEpisodeEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(EpisodeEntityFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageEpisodeEntityToJSON(value?: PageEpisodeEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(EpisodeEntityToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

