/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { ShowEntity } from './ShowEntity';
import {
    ShowEntityFromJSON,
    ShowEntityFromJSONTyped,
    ShowEntityToJSON,
} from './ShowEntity';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageShowEntity
 */
export interface PageShowEntity {
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageShowEntity
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    size?: number;
    /**
     * 
     * @type {Array<ShowEntity>}
     * @memberof PageShowEntity
     */
    content?: Array<ShowEntity>;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageShowEntity
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageShowEntity interface.
 */
export function instanceOfPageShowEntity(value: object): boolean {
    return true;
}

export function PageShowEntityFromJSON(json: any): PageShowEntity {
    return PageShowEntityFromJSONTyped(json, false);
}

export function PageShowEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageShowEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ShowEntityFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageShowEntityToJSON(value?: PageShowEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ShowEntityToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

