/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { ShowEntity } from './ShowEntity';
import {
    ShowEntityFromJSON,
    ShowEntityFromJSONTyped,
    ShowEntityToJSON,
} from './ShowEntity';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageShowEntity
 */
export interface PageShowEntity {
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageShowEntity
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    last?: boolean;
    /**
     * 
     * @type {SortObject}
     * @memberof PageShowEntity
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageShowEntity
     */
    size?: number;
    /**
     * 
     * @type {Array<ShowEntity>}
     * @memberof PageShowEntity
     */
    content?: Array<ShowEntity>;
    /**
     * 
     * @type {boolean}
     * @memberof PageShowEntity
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageShowEntity interface.
 */
export function instanceOfPageShowEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageShowEntityFromJSON(json: any): PageShowEntity {
    return PageShowEntityFromJSONTyped(json, false);
}

export function PageShowEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageShowEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'pageable': !exists(json, 'pageable') ? undefined : PageableObjectFromJSON(json['pageable']),
        'numberOfElements': !exists(json, 'numberOfElements') ? undefined : json['numberOfElements'],
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
        'sort': !exists(json, 'sort') ? undefined : SortObjectFromJSON(json['sort']),
        'number': !exists(json, 'number') ? undefined : json['number'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(ShowEntityFromJSON)),
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function PageShowEntityToJSON(value?: PageShowEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'pageable': PageableObjectToJSON(value.pageable),
        'numberOfElements': value.numberOfElements,
        'first': value.first,
        'last': value.last,
        'sort': SortObjectToJSON(value.sort),
        'number': value.number,
        'size': value.size,
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(ShowEntityToJSON)),
        'empty': value.empty,
    };
}

