/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayQueueItemEntity } from './PlayQueueItemEntity';
import {
    PlayQueueItemEntityFromJSON,
    PlayQueueItemEntityFromJSONTyped,
    PlayQueueItemEntityToJSON,
} from './PlayQueueItemEntity';
import type { UserEntity } from './UserEntity';
import {
    UserEntityFromJSON,
    UserEntityFromJSONTyped,
    UserEntityToJSON,
} from './UserEntity';

/**
 * 
 * @export
 * @interface PlayQueueEntity
 */
export interface PlayQueueEntity {
    /**
     * 
     * @type {string}
     * @memberof PlayQueueEntity
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlayQueueEntity
     */
    dateCreated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlayQueueEntity
     */
    dateUpdated?: Date;
    /**
     * 
     * @type {UserEntity}
     * @memberof PlayQueueEntity
     */
    userEntity?: UserEntity;
    /**
     * 
     * @type {string}
     * @memberof PlayQueueEntity
     */
    currentItem?: string;
    /**
     * 
     * @type {Array<PlayQueueItemEntity>}
     * @memberof PlayQueueEntity
     */
    items?: Array<PlayQueueItemEntity>;
}

/**
 * Check if a given object implements the PlayQueueEntity interface.
 */
export function instanceOfPlayQueueEntity(value: object): boolean {
    return true;
}

export function PlayQueueEntityFromJSON(json: any): PlayQueueEntity {
    return PlayQueueEntityFromJSONTyped(json, false);
}

export function PlayQueueEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayQueueEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateCreated': json['dateCreated'] == null ? undefined : (new Date(json['dateCreated'])),
        'dateUpdated': json['dateUpdated'] == null ? undefined : (new Date(json['dateUpdated'])),
        'userEntity': json['userEntity'] == null ? undefined : UserEntityFromJSON(json['userEntity']),
        'currentItem': json['currentItem'] == null ? undefined : json['currentItem'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PlayQueueItemEntityFromJSON)),
    };
}

export function PlayQueueEntityToJSON(value?: PlayQueueEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'dateCreated': value['dateCreated'] == null ? undefined : ((value['dateCreated']).toISOString()),
        'dateUpdated': value['dateUpdated'] == null ? undefined : ((value['dateUpdated']).toISOString()),
        'userEntity': UserEntityToJSON(value['userEntity']),
        'currentItem': value['currentItem'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PlayQueueItemEntityToJSON)),
    };
}

