/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayQueueItemEntity
 */
export interface PlayQueueItemEntity {
    /**
     * 
     * @type {string}
     * @memberof PlayQueueItemEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayQueueItemEntity
     */
    itemId: string;
}

/**
 * Check if a given object implements the PlayQueueItemEntity interface.
 */
export function instanceOfPlayQueueItemEntity(value: object): boolean {
    if (!('itemId' in value)) return false;
    return true;
}

export function PlayQueueItemEntityFromJSON(json: any): PlayQueueItemEntity {
    return PlayQueueItemEntityFromJSONTyped(json, false);
}

export function PlayQueueItemEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayQueueItemEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'itemId': json['itemId'],
    };
}

export function PlayQueueItemEntityToJSON(value?: PlayQueueItemEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'itemId': value['itemId'],
    };
}

