/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TVShow } from './TVShow';
import {
    TVShowFromJSON,
    TVShowFromJSONTyped,
    TVShowToJSON,
} from './TVShow';

/**
 * 
 * @export
 * @interface Season
 */
export interface Season {
    /**
     * 
     * @type {string}
     * @memberof Season
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Season
     */
    number?: number;
    /**
     * 
     * @type {TVShow}
     * @memberof Season
     */
    tvshow?: TVShow;
}

/**
 * Check if a given object implements the Season interface.
 */
export function instanceOfSeason(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeasonFromJSON(json: any): Season {
    return SeasonFromJSONTyped(json, false);
}

export function SeasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Season {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'tvshow': !exists(json, 'tvshow') ? undefined : TVShowFromJSON(json['tvshow']),
    };
}

export function SeasonToJSON(value?: Season | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'tvshow': TVShowToJSON(value.tvshow),
    };
}

