/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShowEntity } from './ShowEntity';
import {
    ShowEntityFromJSON,
    ShowEntityFromJSONTyped,
    ShowEntityToJSON,
} from './ShowEntity';

/**
 * 
 * @export
 * @interface SeasonEntity
 */
export interface SeasonEntity {
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    id?: string;
    /**
     * 
     * @type {ShowEntity}
     * @memberof SeasonEntity
     */
    showEntity: ShowEntity;
    /**
     * 
     * @type {number}
     * @memberof SeasonEntity
     */
    number: number;
}

/**
 * Check if a given object implements the SeasonEntity interface.
 */
export function instanceOfSeasonEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "showEntity" in value;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function SeasonEntityFromJSON(json: any): SeasonEntity {
    return SeasonEntityFromJSONTyped(json, false);
}

export function SeasonEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'showEntity': ShowEntityFromJSON(json['showEntity']),
        'number': json['number'],
    };
}

export function SeasonEntityToJSON(value?: SeasonEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'showEntity': ShowEntityToJSON(value.showEntity),
        'number': value.number,
    };
}

