/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShowEntity } from './ShowEntity';
import {
    ShowEntityFromJSON,
    ShowEntityFromJSONTyped,
    ShowEntityToJSON,
} from './ShowEntity';

/**
 * 
 * @export
 * @interface SeasonEntity
 */
export interface SeasonEntity {
    /**
     * 
     * @type {string}
     * @memberof SeasonEntity
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SeasonEntity
     */
    dateCreated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SeasonEntity
     */
    dateUpdated?: Date;
    /**
     * 
     * @type {ShowEntity}
     * @memberof SeasonEntity
     */
    showEntity?: ShowEntity;
    /**
     * 
     * @type {number}
     * @memberof SeasonEntity
     */
    number?: number;
}

/**
 * Check if a given object implements the SeasonEntity interface.
 */
export function instanceOfSeasonEntity(value: object): boolean {
    return true;
}

export function SeasonEntityFromJSON(json: any): SeasonEntity {
    return SeasonEntityFromJSONTyped(json, false);
}

export function SeasonEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateCreated': json['dateCreated'] == null ? undefined : (new Date(json['dateCreated'])),
        'dateUpdated': json['dateUpdated'] == null ? undefined : (new Date(json['dateUpdated'])),
        'showEntity': json['showEntity'] == null ? undefined : ShowEntityFromJSON(json['showEntity']),
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function SeasonEntityToJSON(value?: SeasonEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'dateCreated': value['dateCreated'] == null ? undefined : ((value['dateCreated']).toISOString()),
        'dateUpdated': value['dateUpdated'] == null ? undefined : ((value['dateUpdated']).toISOString()),
        'showEntity': ShowEntityToJSON(value['showEntity']),
        'number': value['number'],
    };
}

