/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EpisodeEntity,
} from '../models/index';
import {
    EpisodeEntityFromJSON,
    EpisodeEntityToJSON,
} from '../models/index';

export interface GetEpisodeRequest {
    id: string;
}

/**
 * 
 */
export class EpisodeControllerApi extends runtime.BaseAPI {

    /**
     */
    async getEpisodeRaw(requestParameters: GetEpisodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EpisodeEntity>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEpisode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episodes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EpisodeEntityFromJSON(jsonValue));
    }

    /**
     */
    async getEpisode(requestParameters: GetEpisodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EpisodeEntity> {
        const response = await this.getEpisodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRecent2Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EpisodeEntity>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episodes/recent`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EpisodeEntityFromJSON));
    }

    /**
     */
    async getRecent2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EpisodeEntity>> {
        const response = await this.getRecent2Raw(initOverrides);
        return await response.value();
    }

}
